### PR TITLE
Add linting script.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
Adds "lint" command.

### CODE REVIEW

**Comment by thelordoftheboards** [comment]
@wtgtybhertgeghgtwtg The current scripts have `./node_modules/.bin/` when they start webpack server and babel in order to insure the version from the local `node-modules` is installed. It was required to be able to run it on Heroku, and also helped keep it separate of any globally installed version, like for instance during the babel 5 to babel 6 transition. I would like to keep it, unless there are some significant reasons not to. Please let me know what you think.

When calling the lint with `eslint app configuration data graphql scripts server units webapp` are there gonna be any implications on Heroku you are aware of?

**Comment by wtgtybhertgeghgtwtg** [comment]
I have yet to test it on Heroku.  I'll try to do that.

**Comment by thelordoftheboards** [comment]
If you like, I will merge it, test on Heroku, and make changes, since I have the rest of the setup. Is this OK with you?

**Comment by wtgtybhertgeghgtwtg** [comment]
That is fine, thank you.

**Comment by wtgtybhertgeghgtwtg** [comment]
As is, it won't work in production, as there are numerous linting errors.

**Pull request merged**
